// Generated by CoffeeScript 1.7.1
(function () {
    var weChatSystem, managementSystem, publicRoute, mobile;
    //weChatSystem = require('../api/WeChatSystem/route');
    managementSystem = require('../api/ManagementSystem/route');
    //mobile = require('../api/Mobile/route');
    publicRoute = require('../api/Public/route');
    module.exports = function (app) {
        //managementSystem(app);
        publicRoute(app);
        //mobile(app);
        return managementSystem(app);
    };

}).call(this);

//# sourceMappingURL=routes.map
